#define VIAL_KEYBOARD_UID {0x39, 0x9F, 0x74, 0xF9, 0x88, 0x68, 0x7C, 0xFE}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {1, 9}

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 4
#define AUTO_MOUSE_TIME 650
#define AUTO_MOUSE_DELAY 200
#define AUTO_MOUSE_DEBOUNCE 25

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_IDLE_TIMEOUT 3000

#ifndef HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#endif

#define USE_LOCAL_KEY_OVERRIDES
