#pragma once

// BACKLIGHT
#define BACKLIGHT_PIN GP10          // The pin that controls the LEDs
#define BACKLIGHT_LEVELS 10         // The number of brightness levels

// RGB LIGHTING
#define RGBLIGHT_LED_COUNT 6        // Number of LEDs
#define RGBLIGHT_DEFAULT_HUE 20     // The default hue to use upon clearing the EEPROM

#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_TWINKLE

// LAYER
#define DYNAMIC_KEYMAP_LAYER_COUNT 10

// CRYSTAL SETTING
#define PICO_XOSC_STARTUP_DELAY_MULTIPLIER 64