#pragma once
#define VIAL_KEYBOARD_UID {0xFC, 0x19, 0x1A, 0x14, 0x42, 0xE0, 0x95, 0x1A}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {1, 11}
#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_IDLE_TIMEOUT 3000

#ifndef HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#endif

#define RGBLIGHT_LAYERS_RETAIN_VAL

#define EECONFIG_USER_DATA_SIZE 39 // 4 byte * 8 layers + 1 byte * 2 flags + 1 byte * 5 = 39
